import express from "express";
import cors from "cors";
import bodyParser from "body-parser";
import { ENV } from "./config";
import cron from "node-cron";
import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";
import { ID_TABLE } from "./constants";
import { parserMatch } from "./service";
import { checkAddMatches, isCheckAddMatches } from "./utils";

const app = express();
// Разблокировать cors
app.use(cors());
// позволяет принимать входящее тело запроса POST
app.use(bodyParser.json());
const port = process.env.PORT || 3001;
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: ENV.EMAIL,
  key: ENV.PASSWORD,
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});

const doc = new GoogleSpreadsheet(ID_TABLE, serviceAccountAuth);

app.listen(port, async () => {
  console.log(`Server listening on port http://localhost:${port}`);

  await doc.loadInfo();
  const sheet = doc.sheetsByIndex[0];
  const rows = await sheet.getRows(); // данные из гугл таблицы
  const matches = await parserMatch.matches;
  const convertGoogleData = parserMatch.convertGoogleRows(rows);
  console.log(matches, 9999, "website matches========>");
  console.log(convertGoogleData, 6666);

  // checkAddMatches([], rows, sheet);
  // console.log(isCheckAddMatches([], convertGoogleData), 999999);
  await sheet.loadCells("A1:K10");
  const budget = sheet.getCell(0, 10); // получаем сумму

  await sheet.saveUpdatedCells();

  // const sheet = await doc.addSheet({ headerValues: ["name", "email"] });
  // append rows
  // const larryRow = await sheet.addRow({
  //   time: "13:12",
  //   date: "13.12",
  // });
  // await sheet.addRows(matches);

  // read rows

  const date = rows[3].get("date");

  // console.log(date, 2222);

  // cron.schedule("00 12 * * *", () => {
  //   console.log("running a task every day in 12:00");
  // });

  // cron.schedule("55 23 * * *", () => {
  //   console.log("running a task every day in 23:55");
  // });

  // cron.schedule("*/5 * * * * *", async () => {
  //   console.log("running a task every 5 secs");
  //   // await sheet.addRows(matches);
  // });
});
